swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Designers
  license:
    name: MIT
host: 127.0.0.1:54434
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /designers:
    x-swagger-router-controller: designers
    get:
      summary: List all designers
      operationId: getDesigners
      tags:
        - designers
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 1000)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: An paged array of designers
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Designers'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a list of designers
      operationId: createDesigners
      tags:
        - designers
      parameters:
        - name: designers
          in: body
          description: Designers list to add
          required: true
          schema:
            $ref: '#/definitions/Designer'
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Designer'
  /designers/{designerId}:
    get:
      summary: Info for a specific designer
      operationId: showDesignerById
      tags:
        - designers
      parameters:
        - name: designerId
          in: path
          required: true
          description: The id of the designer to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Designer'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Designer:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: uint64
      name:
        type: string
      surname:
        type: string
      email:
        type: string
      phone:
        type: string
      summary:
        type: string
      tag:
        type: string
  Designers:
    type: array
    items:
      $ref: '#/definitions/Designer'
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
